### ISSUE TITLE
In Rider IDE settings are not saved

### ISSUE THREAD

**Issue by duchacekjan** [mai-space/plugin-phpstorm-typo3-commit-template#29]
When I set something in rider ide plugin settings i.e. check Use the subject line, then hit save and open setting page again, checkbox is not set.

**Comment by mai-space** [comment]
You are right! 

I never really finished the persistence issue... I will fix that soon

**Comment by duchacekjan** [comment]
I am using the latest version. 2023.2.2

**Comment by mai-space** [comment]
Perfect. I am still struggling with quodana, a linter for jetbrains ide plugins... I'll try to debug it locally but the pipeline output is not very helpful. The moment this is fixed, I'll release the patch

**Comment by mai-space** [comment]
Whuup Whuup 🥳

The deployment seams to be fixed. Only some optimization and I can release it
