### ISSUE TITLE
Feature request: Editable pattern for issue nr.

### ISSUE THREAD

**Issue by duchacekjan** [mai-space/plugin-phpstorm-typo3-commit-template#30]
Now in plugin can be extracted issue nr. from branch but only pulls number. It would be nice to have editable pattern to get issue number from branch. Perfect would be regex.
We use issue tracking with prefixes. I.E. MTZ-233 and branch is named as feature/MTZ-233_adding_new_grid

**Comment by mai-space** [comment]
I will look into this :)

**Comment by mai-space** [comment]
The feature is implemented and some more fixes on the way. 

As said in the other issue, only the release is still in development.

**Comment by mai-space** [comment]
Whuup Whuup 🥳

The deployment seams to be fixed. Only some optimization and I can release it
